import type { DisplayMessage, SourceInfo } from '../shared/types'
import { renderMarkdown } from './markdown'

export type Panel = {
  setSetup(): void
  setIdle(onRun: () => void): void
  setLoading(message: string): void
  setSources(sources: SourceInfo[]): void
  appendToken(text: string): void
  finish(onRerun?: () => void): void
  setError(message: string, onRetry: () => void): void
  addUserMessage(text: string): void
  beginExchange(): void
  enableChat(onAsk: (question: string) => void): void
  restore(display: DisplayMessage[], sources: SourceInfo[]): void
}

const CSS = `
:host { all: initial; display: block; }
.card { font: 14px/1.55 system-ui, -apple-system, sans-serif; color: #1a1a1a; background: #fff;
  border: 1px solid #dcdfe4; border-radius: 12px; padding: 14px 16px; margin: 0 0 16px;
  box-shadow: 0 1px 3px rgba(0,0,0,.06); }
@media (prefers-color-scheme: dark) {
  .card { background: #1e2128; color: #e6e6e6; border-color: #3a3f4a; }
  .card a { color: #8ab4f8; }
  .chatrow input { background: #2a2e37; color: #e6e6e6; border-color: #3a3f4a; }
}
.card a { color: #3367d6; }
.head { display: flex; align-items: center; gap: 8px; font-weight: 600; font-size: 13px; margin-bottom: 8px; }
.head .grow { flex: 1; }
.body p { margin: 0 0 8px; }
.body ul, .body ol { margin: 0 0 8px 18px; padding: 0; }
.body h3, .body h4, .body h5, .body h6 { margin: 10px 0 6px; font-size: 14px; }
.body code { background: rgba(127,127,127,.15); border-radius: 4px; padding: 1px 4px; font-size: 12px; font-family: monospace; }
.body pre { background: rgba(127,127,127,.12); border-radius: 8px; padding: 10px; overflow-x: auto; }
.body pre code { background: none; padding: 0; }
sup.cite a { text-decoration: none; font-weight: 600; padding: 0 1px; }
.user-q { font-weight: 600; margin: 12px 0 6px; padding: 8px 10px; background: rgba(127,127,127,.08); border-radius: 8px; }
.chatrow { display: flex; gap: 8px; margin-top: 12px; }
.chatrow input { flex: 1; padding: 8px 10px; border: 1px solid #c9cdd4; border-radius: 8px; font: inherit; background: transparent; color: inherit; }
.chatrow input:disabled { opacity: .5; }
.sources { display: flex; gap: 6px; align-items: center; margin-top: 10px; flex-wrap: wrap; font-size: 12px; opacity: .85; }
.sources img { width: 16px; height: 16px; border-radius: 4px; vertical-align: middle; }
.foot { margin-top: 10px; font-size: 11px; opacity: .6; display: flex; justify-content: space-between; align-items: center; gap: 8px; }
button.wc { cursor: pointer; border: 1px solid #c9cdd4; background: transparent; color: inherit;
  border-radius: 8px; padding: 5px 12px; font: inherit; font-size: 12px; }
button.wc:hover { background: rgba(127,127,127,.1); }
.shimmer { animation: wc-pulse 1.2s ease-in-out infinite; }
@keyframes wc-pulse { 0%, 100% { opacity: .75; } 50% { opacity: .3; } }
.err { color: #d93025; }
`

function faviconUrl(pageUrl: string): string {
  try {
    return `https://icons.duckduckgo.com/ip3/${new URL(pageUrl).hostname}.ico`
  } catch {
    return ''
  }
}

type Exchange = { el: HTMLElement; markdown: string; queued: boolean }

export function createPanel(host: HTMLElement, meta: { model: string; endpointHost: string }): Panel {
  const root = host.attachShadow({ mode: 'open' })
  const style = document.createElement('style')
  style.textContent = CSS
  const card = document.createElement('div')
  card.className = 'card'
  card.innerHTML = `
    <div class="head"><span>✨ AI Overview</span><span class="grow"></span>
      <button class="wc toggle" title="Collapse">–</button></div>
    <div class="content">
      <div class="body"></div>
      <div class="chatslot"></div>
      <div class="sources"></div>
      <div class="foot">
        <span class="meta"></span>
        <span class="actions"></span>
      </div>
    </div>`
  root.append(style, card)

  const body = card.querySelector('.body') as HTMLElement
  const chatSlot = card.querySelector('.chatslot') as HTMLElement
  const sourcesEl = card.querySelector('.sources') as HTMLElement
  const metaEl = card.querySelector('.meta') as HTMLElement
  const actionsEl = card.querySelector('.actions') as HTMLElement
  const content = card.querySelector('.content') as HTMLElement
  const toggle = card.querySelector('.toggle') as HTMLButtonElement
  toggle.addEventListener('click', () => {
    const hidden = content.style.display === 'none'
    content.style.display = hidden ? '' : 'none'
    toggle.textContent = hidden ? '–' : '+'
  })
  metaEl.textContent = `generated by ${meta.model} via ${meta.endpointHost}`

  let citations = new Map<number, string>()
  let current: Exchange | null = null
  let chatInput: HTMLInputElement | null = null
  let chatHandler: ((q: string) => void) | null = null
  let onRerunSaved: (() => void) | null = null

  const button = (label: string, onClick: () => void) => {
    const b = document.createElement('button')
    b.className = 'wc'
    b.textContent = label
    b.addEventListener('click', onClick)
    return b
  }

  const shimmer = (message: string) => {
    const p = document.createElement('p')
    p.className = 'shimmer'
    p.textContent = message
    return p
  }

  const newExchange = (loadingMessage: string): Exchange => {
    // If the previous exchange is still an untouched loading block (no content
    // yet, still shimmering), it has no owner — drop it instead of orphaning it.
    if (current && current.markdown === '' && current.el.querySelector('.shimmer')) {
      current.el.remove()
      current.queued = false
    }
    const el = document.createElement('div')
    el.className = 'exchange'
    el.append(shimmer(loadingMessage))
    body.append(el)
    current = { el, markdown: '', queued: false }
    return current
  }

  const renderExchange = (ex: Exchange) => {
    // The queued flag gates execution, not just scheduling: a frame registered
    // before setError (or any DOM replacement) must no-op instead of wiping it.
    if (!ex.queued) return
    ex.queued = false
    ex.el.innerHTML = renderMarkdown(ex.markdown, citations)
  }
  const scheduleRender = (ex: Exchange) => {
    if (ex.queued) return
    ex.queued = true
    requestAnimationFrame(() => renderExchange(ex))
  }

  const setChatDisabled = (disabled: boolean) => {
    if (chatInput) chatInput.disabled = disabled
  }

  // Implementations kept as plain closures (not `this`-bound methods) so they can
  // be shared by both the public methods and restore() without relying on `this`.
  const setSourcesImpl = (sources: SourceInfo[]) => {
    citations = new Map(sources.map(s => [s.index, s.url]))
    sourcesEl.replaceChildren(
      ...sources.filter(s => s.ok).map(s => {
        const a = document.createElement('a')
        a.href = s.url
        a.target = '_blank'
        a.rel = 'noopener'
        a.title = s.title
        const img = document.createElement('img')
        img.src = faviconUrl(s.url)
        img.alt = ''
        a.append(img)
        return a
      }),
    )
    const failed = sources.filter(s => !s.ok).length
    if (failed) {
      const note = document.createElement('span')
      note.textContent = `(${failed} source${failed > 1 ? 's' : ''} unavailable)`
      sourcesEl.append(note)
    }
  }

  const addUserMessageImpl = (text: string) => {
    const q = document.createElement('div')
    q.className = 'user-q'
    q.textContent = text
    body.append(q)
  }

  const resetAll = () => {
    body.replaceChildren()
    sourcesEl.replaceChildren()
    actionsEl.replaceChildren()
    chatSlot.replaceChildren()
    chatInput = null
    chatHandler = null
    current = null
    citations = new Map()
    onRerunSaved = null
  }

  return {
    setSetup() {
      body.innerHTML = '<p><strong>Webcrawla isn’t configured yet.</strong> Add your endpoint, API key and model to get AI overviews here.</p>'
      actionsEl.replaceChildren(button('Open settings', () => {
        chrome.runtime.sendMessage({ target: 'background', kind: 'open-options' })
      }))
    },
    setIdle(onRun) {
      body.replaceChildren(button('✨ Summarize these results', onRun))
      actionsEl.replaceChildren()
    },
    setLoading(message) {
      if (!current) {
        // First loading call of a fresh card (summary path): start clean.
        body.replaceChildren()
        newExchange(message)
      } else if (current.markdown === '') {
        current.el.replaceChildren(shimmer(message))
      }
      actionsEl.replaceChildren()
      setChatDisabled(true)
    },
    setSources(sources) {
      setSourcesImpl(sources)
    },
    appendToken(text) {
      if (!current) newExchange('')
      if (current!.markdown === '') current!.el.replaceChildren() // clear shimmer on first token
      current!.markdown += text
      scheduleRender(current!)
    },
    finish(onRerun) {
      if (current) {
        // Guarantee a final render regardless of any pending/consumed frame.
        current.queued = true
        renderExchange(current)
      }
      actionsEl.replaceChildren()
      const rerun = onRerun ?? onRerunSaved
      if (rerun) {
        onRerunSaved = rerun
        actionsEl.append(button('↻ Regenerate', () => {
          resetAll()
          rerun()
        }))
      }
      setChatDisabled(false)
    },
    setError(message, onRetry) {
      const ex = current ?? newExchange('')
      const p = document.createElement('p')
      p.className = 'err'
      p.textContent = message
      const retry = button('Retry', () => {
        ex.el.remove()
        if (current === ex) current = null
        onRetry()
      })
      const children: HTMLElement[] = [p, retry]
      if (onRerunSaved) {
        const rerun = onRerunSaved
        children.push(button('↻ Regenerate', () => {
          resetAll()
          rerun()
        }))
      }
      ex.el.replaceChildren(...children)
      ex.markdown = ''
      // Cancel any frame already registered for this exchange so it can't run
      // later and overwrite the error + Retry UI with empty markdown.
      ex.queued = false
      actionsEl.replaceChildren()
      setChatDisabled(false)
    },
    addUserMessage(text) {
      addUserMessageImpl(text)
    },
    beginExchange() {
      newExchange('Thinking…')
      actionsEl.replaceChildren()
      setChatDisabled(true)
    },
    enableChat(onAsk) {
      chatHandler = onAsk
      if (chatInput) return // row already exists; handler updated above
      const row = document.createElement('div')
      row.className = 'chatrow'
      const input = document.createElement('input')
      input.type = 'text'
      input.placeholder = 'Ask a follow-up…'
      const submit = () => {
        const q = input.value.trim()
        if (!q || input.disabled || !chatHandler) return
        input.value = ''
        chatHandler(q)
      }
      input.addEventListener('keydown', e => {
        if (e.key === 'Enter') submit()
      })
      const ask = button('Ask', submit)
      row.append(input, ask)
      chatSlot.replaceChildren(row)
      chatInput = input
    },
    restore(display, sources) {
      body.replaceChildren()
      current = null
      setSourcesImpl(sources)
      for (const msg of display) {
        if (msg.role === 'user') {
          addUserMessageImpl(msg.markdown)
        } else {
          const el = document.createElement('div')
          el.className = 'exchange'
          el.innerHTML = renderMarkdown(msg.markdown, citations)
          body.append(el)
        }
      }
    },
  }
}
