import type { SourceInfo } from '../shared/types'
import { renderMarkdown } from './markdown'

export type Panel = {
  setSetup(): void
  setIdle(onRun: () => void): void
  setLoading(message: string): void
  setSources(sources: SourceInfo[]): void
  appendToken(text: string): void
  finish(): void
  setError(message: string, onRetry: () => void): void
}

const CSS = `
:host { all: initial; display: block; }
.card { font: 14px/1.55 system-ui, -apple-system, sans-serif; color: #1a1a1a; background: #fff;
  border: 1px solid #dcdfe4; border-radius: 12px; padding: 14px 16px; margin: 0 0 16px;
  box-shadow: 0 1px 3px rgba(0,0,0,.06); }
@media (prefers-color-scheme: dark) {
  .card { background: #1e2128; color: #e6e6e6; border-color: #3a3f4a; }
  .card a { color: #8ab4f8; }
}
.card a { color: #3367d6; }
.head { display: flex; align-items: center; gap: 8px; font-weight: 600; font-size: 13px; margin-bottom: 8px; }
.head .grow { flex: 1; }
.body p { margin: 0 0 8px; }
.body ul, .body ol { margin: 0 0 8px 18px; padding: 0; }
.body h3, .body h4, .body h5, .body h6 { margin: 10px 0 6px; font-size: 14px; }
.body code { background: rgba(127,127,127,.15); border-radius: 4px; padding: 1px 4px; font-size: 12px; font-family: monospace; }
.body pre { background: rgba(127,127,127,.12); border-radius: 8px; padding: 10px; overflow-x: auto; }
.body pre code { background: none; padding: 0; }
sup.cite a { text-decoration: none; font-weight: 600; padding: 0 1px; }
.sources { display: flex; gap: 6px; align-items: center; margin-top: 10px; flex-wrap: wrap; font-size: 12px; opacity: .85; }
.sources img { width: 16px; height: 16px; border-radius: 4px; vertical-align: middle; }
.foot { margin-top: 10px; font-size: 11px; opacity: .6; display: flex; justify-content: space-between; align-items: center; gap: 8px; }
button.wc { cursor: pointer; border: 1px solid #c9cdd4; background: transparent; color: inherit;
  border-radius: 8px; padding: 5px 12px; font: inherit; font-size: 12px; }
button.wc:hover { background: rgba(127,127,127,.1); }
.shimmer { animation: wc-pulse 1.2s ease-in-out infinite; }
@keyframes wc-pulse { 0%, 100% { opacity: .75; } 50% { opacity: .3; } }
.err { color: #d93025; }
`

function faviconUrl(pageUrl: string): string {
  try {
    return `https://icons.duckduckgo.com/ip3/${new URL(pageUrl).hostname}.ico`
  } catch {
    return ''
  }
}

export function createPanel(host: HTMLElement, meta: { model: string; endpointHost: string }): Panel {
  const root = host.attachShadow({ mode: 'open' })
  const style = document.createElement('style')
  style.textContent = CSS
  const card = document.createElement('div')
  card.className = 'card'
  card.innerHTML = `
    <div class="head"><span>✨ AI Overview</span><span class="grow"></span>
      <button class="wc toggle" title="Collapse">–</button></div>
    <div class="content">
      <div class="body"></div>
      <div class="sources"></div>
      <div class="foot">
        <span class="meta"></span>
        <span class="actions"></span>
      </div>
    </div>`
  root.append(style, card)

  const body = card.querySelector('.body') as HTMLElement
  const sourcesEl = card.querySelector('.sources') as HTMLElement
  const metaEl = card.querySelector('.meta') as HTMLElement
  const actionsEl = card.querySelector('.actions') as HTMLElement
  const content = card.querySelector('.content') as HTMLElement
  const toggle = card.querySelector('.toggle') as HTMLButtonElement
  toggle.addEventListener('click', () => {
    const hidden = content.style.display === 'none'
    content.style.display = hidden ? '' : 'none'
    toggle.textContent = hidden ? '–' : '+'
  })
  metaEl.textContent = `generated by ${meta.model} via ${meta.endpointHost}`

  let markdown = ''
  let citations = new Map<number, string>()
  let renderQueued = false

  const render = () => {
    renderQueued = false
    body.innerHTML = renderMarkdown(markdown, citations)
  }
  const scheduleRender = () => {
    if (renderQueued) return
    renderQueued = true
    requestAnimationFrame(render)
  }
  const button = (label: string, onClick: () => void) => {
    const b = document.createElement('button')
    b.className = 'wc'
    b.textContent = label
    b.addEventListener('click', onClick)
    return b
  }

  return {
    setSetup() {
      body.innerHTML = '<p><strong>Webcrawla isn\'t configured yet.</strong> Add your endpoint, API key and model to get AI overviews here.</p>'
      actionsEl.replaceChildren(button('Open settings', () => {
        chrome.runtime.sendMessage({ target: 'background', kind: 'open-options' })
      }))
    },
    setIdle(onRun) {
      body.innerHTML = ''
      actionsEl.replaceChildren()
      body.replaceChildren(button('✨ Summarize these results', onRun))
    },
    setLoading(message) {
      const p = document.createElement('p')
      p.className = 'shimmer'
      p.textContent = message
      if (!markdown) body.replaceChildren(p)
      actionsEl.replaceChildren()
    },
    setSources(sources) {
      citations = new Map(sources.map(s => [s.index, s.url]))
      sourcesEl.replaceChildren(
        ...sources.filter(s => s.ok).map(s => {
          const a = document.createElement('a')
          a.href = s.url
          a.target = '_blank'
          a.rel = 'noopener'
          a.title = s.title
          const img = document.createElement('img')
          img.src = faviconUrl(s.url)
          img.alt = ''
          a.append(img)
          return a
        }),
      )
      const failed = sources.filter(s => !s.ok).length
      if (failed) {
        const note = document.createElement('span')
        note.textContent = `(${failed} source${failed > 1 ? 's' : ''} unavailable)`
        sourcesEl.append(note)
      }
    },
    appendToken(text) {
      if (!markdown) body.replaceChildren() // clear shimmer on first token
      markdown += text
      scheduleRender()
    },
    finish() {
      render()
      actionsEl.replaceChildren()
    },
    setError(message, onRetry) {
      const p = document.createElement('p')
      p.className = 'err'
      p.textContent = message
      body.replaceChildren(p)
      actionsEl.replaceChildren(button('Retry', onRetry))
    },
  }
}
